name: TeleportPlaces
main: com.example.teleport.TeleportPlugin
version: 1.0
api-version: 1.12
author: you
commands:
  t:
    description: テレポートコマンド。/t <番号> /t add /t set /t list /t remove
    usage: /t <番号> | /t add | /t set <番号> <名前> | /t list | /t remove <番号>
    permission-message: "You don't have permission to use this command."
